### ISSUE TITLE
crash when using datawatcher on Windows

### ISSUE THREAD

**Issue by sverkoye** [danielstjules/geoip-ultralight#1]
Perhaps problems on other platforms also, not tested. Quick fix for anyone interested:
In fsWatcher.js find this line:
var filePath = path.join(directory, changedFile);
change to:
var filePath = path.join(directory, changedFile || '**no__file_passed__with_event**');

**Comment by danielstjules** [comment]
Thanks for letting me know! That bit of code is also [present upstream](https://github.com/bluesmoon/node-geoip/blob/b1c38bbab196807a2d0d5cbca494f328686a35f4/lib/fsWatcher.js#L28).
