### ISSUE TITLE
Regular Expression Denial of Service vulnerability in minimatch module

### ISSUE THREAD

**Issue by nirmalgupta** [danielstjules/geoip-ultralight#3]
geoip-ultralight uses glob@3.2.11, which in turn uses minimatch@0.3.0. Recently there was vulnerability reported on nsp site. 

 https://nodesecurity.io/advisories/118   

Can you please upgrade your dependency of globe@3.2.11.

Thanks.

**Comment by danielstjules** [comment]
It's actually not used at all, so there's no security concern. I'll update and remove the package as a dependency later, thanks! :)

**Comment by nirmalgupta** [comment]
Thanks... :)
