### ISSUE TITLE
updatedb doesn't always work

### ISSUE THREAD

**Issue by srussellextensis** [danielstjules/geoip-ultralight#4]
When trying to update the country databases, sometimes the update script exits early without any error being reported:

```
$ npm run-script updatedb

> geoip-ultralight@0.1.4 updatedb /Users/srussell/Documents/work/git/data-collector/node_modules/geoip-ultralight
> node scripts/updatedb.js

Retrieving GeoIPCountryCSV.zip ... DONE
Extracting GeoIPCountryCSV.zip ...
```

It seems like the file was unzipped properly, since it matches the size of the file when the script does work correctly. It's just that the post-processing of that file doesn't happen and the IPv6 data isn't processed at all.

This happens on two different Mac OS X 10.11 machines, one running node 6.4.0, the other running 4.4.6.

**Comment by danielstjules** [comment]
Unfortunately, I haven't been able to replicate this issue on my machine. Looking at https://github.com/danielstjules/geoip-ultralight/blob/master/scripts/updatedb.js#L141-L159 is it possible the temp file wasn't created, or maybe the permissions are wrong?

In any case, I've updated the .dat files and published a new release!
